import streamlit as st
from pathlib import Path
from agent import run_research_pipeline

st.set_page_config(page_title="Multi-Modal Research Agent", page_icon="🤖", layout="wide")

PAGE_STYLE = """
<style>
body {
    background-color: #eef2ff;
}
section.main {
    padding-top: 1rem;
}
div.block-container {
    padding-top: 1rem;
    max-width: 1100px;
}
.stButton>button {
    border-radius: 999px;
    background-color: #4f46e5;
    color: white;
    padding: 0.85rem 1.5rem;
    border: none;
}
.stTextInput>div>div>input {
    border-radius: 18px;
    padding: 1rem 1rem;
}
.stMarkdown {
    font-size: 1rem;
    line-height: 1.75;
}
.stMarkdown h1, .stMarkdown h2, .stMarkdown h3 {
    color: #111827;
}
.stMarkdown blockquote {
    border-left: 4px solid #c7d2fe;
    padding-left: 1rem;
    color: #334155;
    background: #eef2ff;
}
</style>
"""


def save_markdown(topic: str, markdown_text: str) -> Path:
    safe_name = "_".join(topic.strip().split()[:6]).replace("/", "_").replace("\\", "_")
    if not safe_name:
        safe_name = "research_paper"
    filename = f"{safe_name}.md"
    path = Path(filename)
    path.write_text(markdown_text, encoding="utf-8")
    return path


def main() -> None:
    st.markdown(PAGE_STYLE, unsafe_allow_html=True)

    st.markdown("""
    <div style='padding: 20px; border-radius: 24px; background: #ffffff; box-shadow: 0 20px 80px rgba(15, 23, 42, 0.08);'>
        <h1 style='margin: 0; color: #111827;'>Multi-Modal Research Agent</h1>
        <p style='color: #475569; font-size: 1.05rem; margin-top: 0.6rem;'>Enter a research topic, then run the pipeline to generate a polished Markdown research paper with a preview and download link.</p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("---")

    with st.container():
        topic = st.text_input(
            "Research topic",
            placeholder="Example: Applications of multimodal agents in scientific discovery",
            key="research_topic",
        )

        if st.button("Run Research Pipeline", type="primary"):
            if not topic.strip():
                st.warning("Please enter a research topic before running the pipeline.")
            else:
                with st.spinner("Running research pipeline... this may take a few minutes"):
                    paper_markdown = run_research_pipeline(topic.strip())
                    st.session_state.paper_markdown = paper_markdown
                    st.session_state.paper_filename = save_markdown(topic.strip(), paper_markdown).name

    if "paper_markdown" in st.session_state and st.session_state.paper_markdown:
        st.markdown("---")
        st.markdown("## Research Paper Output")
        st.write(f"**File:** `{st.session_state.paper_filename}`")

        st.download_button(
            label="Download Markdown Research Paper",
            data=st.session_state.paper_markdown,
            file_name=st.session_state.paper_filename,
            mime="text/markdown",
        )

        st.markdown("### Paper Preview")
        st.markdown(st.session_state.paper_markdown)

        st.info("The research paper was generated by the pipeline and is rendered here in Markdown format.")


if __name__ == "__main__":
    main()
